// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

//import "gorm.io/gorm"

const TableNameItem = "items"

// Item mapped from table <items>
type Item struct {
	//gorm.Model
	ItemName  string `gorm:"column:item_name;not null" json:"item_name"`
	ItemId string `gorm:"column:item_id;not null" json:"item_id"`
	Price int    `gorm:"column:price;not null" json:"price"`
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
