// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserItem = "user_items"

// UserItem mapped from table <user_items>
type UserItem struct {
}

// TableName UserItem's table name
func (*UserItem) TableName() string {
	return TableNameUserItem
}
