// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserId   string `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	UserName string `gorm:"column:name;not null" json:"username"`
	CreatedAt string `gorm:"column:created_at" json:"created_at"`
	UpdatedAt string `gorm:"column:updated_at" json:"updated_at"`
	Items []Item `gorm:"foreignKey:ItemId" json:"items"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
